.\" Copyright 1988 by the Massachusetts Institute of Technology.  For
.\" copying and distribution information, see the file <mit-copyright.h>.
.\"
.\" Original version by Steve Dyer, IBM/Project Athena.
.\"
.\"	$Author: lwvanels $
.\"	$Source: /afs/dev.mit.edu/source/repository/athena/lib/hesiod/hesiod.3,v $
.\"	$Athena: hesiod.3,v 1.3 88/08/07 21:52:25 treese Locked $
.\"	$Header: /afs/dev.mit.edu/source/repository/athena/lib/hesiod/hesiod.3,v 1.7 1991-08-15 14:15:28 lwvanels Exp $
.TH HESIOD 3 "2 April 1987"
.SH NAME
hesiod \- C Language Hesiod name server Interface Library
.SH SYNOPSIS
.nf
.B #include <hesiod.h>
.PP
.B char **hes_resolve(name, HesiodNameType)
.B char *name, *HesiodNameType;
.PP
.B int hes_error()
.PP
.B cc file.c -lhesiod
.PP
.SH DESCRIPTION
.I hes_resolve
is the primary interface to the Hesiod name server.
It takes two arguments, a name to be resolved and a string, known
as a HesiodNameType.  It returns a NULL terminated vector of
strings (a la argv), one for each resource record
containing Hesiod data, or NULL if there is any error.  The
function
.I hes_error
may be called to determine the source of the error.  It will return
one of the HES_ER_* codes defined in
.I hesiod.h.

If the environment variable
.B HES_DOMAIN
is set, this domain will override what is in /etc/athena/hesiod.conf.
.SH FILES
/usr/athena/include/hesiod.h, /etc/athena/hesiod.conf
.SH "SEE ALSO"
`Hesiod - Project Athena Technical Plan -- Name Service', named(8)
.SH AUTHOR
Steve Dyer, IBM/Project Athena
.br
Copyright 1987, 1988 by the Massachusetts Institute of Technology.
.br
.SH BUGS
